import type { CVData } from '../types/cv.types';

export const SAMPLE_CV: CVData = {
  id: 'sample-cv-001',
  title: 'CV - Ingeniero de Software Senior',
  createdAt: '2026-01-15T10:00:00.000Z',
  updatedAt: '2026-10-07T18:00:00.000Z',
  personalInfo: {
    fullName: 'Alejandro Morales Rivera',
    jobTitle: 'Senior Full Stack Software Engineer',
    email: 'alejandro.morales@example.com',
    phone: '+34 612 345 678',
    location: 'Madrid, España',
    website: 'https://alejandromorales.dev',
    linkedin: 'https://linkedin.com/in/alejandro-morales-dev',
    github: 'https://github.com/amorales-dev',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    summary:
      'Ingeniero de Software con más de 7 años de experiencia diseñando y escalando aplicaciones web de alto rendimiento. Especializado en ecosistemas React, TypeScript, Node.js y arquitecturas cloud orientadas a microservicios. Apasionado por la calidad del código, el diseño de sistemas resilientes y el liderazgo técnico de equipos ágiles.',
  },
  experiences: [
    {
      id: 'exp-1',
      company: 'NovaTech Solutions',
      role: 'Lead Full Stack Engineer',
      location: 'Madrid, España (Híbrido)',
      startDate: '2023-03',
      endDate: undefined,
      isCurrent: true,
      description:
        'Liderazgo técnico del equipo de plataforma core, responsable de la arquitectura frontend y servicios backend.',
      bulletPoints: [
        'Lideré la migración de un monolito legacy a una arquitectura modular con React, Vite y TypeScript, reduciendo los tiempos de carga en un 42%.',
        'Diseñé e implementé un sistema de caché distribuido que disminuyó la latencia de las APIs críticas en un 35%.',
        'Mentoré a un equipo de 6 desarrolladores frontend y backend, implementando revisiones de código y pruebas automatizadas con cobertura superior al 85%.',
      ],
    },
    {
      id: 'exp-2',
      company: 'Global Cloud Systems',
      role: 'Senior Software Developer',
      location: 'Barcelona, España',
      startDate: '2020-02',
      endDate: '2023-02',
      isCurrent: false,
      description:
        'Desarrollo de módulos clave para una plataforma SaaS multi-tenant con más de 100,000 usuarios activos mensuales.',
      bulletPoints: [
        'Desarrollé dashboards analíticos en tiempo real utilizando React, WebSockets y visualizaciones interactivas de alto rendimiento.',
        'Optimicé pipelines de CI/CD en GitHub Actions y AWS ECS, acelerando la frecuencia de despliegues de semanal a múltiples veces por día.',
        'Colaboré estrechamente con diseñadores de producto para implementar un Design System accesible (WCAG AA).',
      ],
    },
    {
      id: 'exp-3',
      company: 'Innova Soft Studio',
      role: 'Frontend Developer',
      location: 'Valencia, España',
      startDate: '2018-06',
      endDate: '2020-01',
      isCurrent: false,
      description:
        'Construcción de interfaces responsivas y aplicaciones web interactivas para clientes internacionales en fintech y ecommerce.',
      bulletPoints: [
        'Construí más de 12 aplicaciones web para comercio electrónico con integración de pasarelas de pago Stripe y PayPal.',
        'Mejoré el SEO técnico y las métricas Core Web Vitals en clientes clave, aumentando el tráfico orgánico promedio en un 28%.',
      ],
    },
  ],
  educations: [
    {
      id: 'edu-1',
      institution: 'Universidad Politécnica de Madrid',
      degree: 'Grado en Ingeniería Informática',
      fieldOfStudy: 'Sistemas Software y Computación',
      location: 'Madrid, España',
      startDate: '2014-09',
      endDate: '2018-06',
      isCurrent: false,
      gpaOrHonors: 'Graduado con Mención de Honor en Proyecto de Fin de Grado',
      description: 'Especialización en arquitectura de software y bases de datos relacionales.',
    },
  ],
  skills: [
    { id: 'sk-1', name: 'TypeScript', category: 'technical', level: 'expert' },
    { id: 'sk-2', name: 'React & Next.js', category: 'technical', level: 'expert' },
    { id: 'sk-3', name: 'Node.js & Express', category: 'technical', level: 'advanced' },
    { id: 'sk-4', name: 'Tailwind CSS', category: 'technical', level: 'expert' },
    { id: 'sk-5', name: 'PostgreSQL & Redis', category: 'technical', level: 'advanced' },
    { id: 'sk-6', name: 'Docker & AWS', category: 'tools', level: 'intermediate' },
    { id: 'sk-7', name: 'Git & GitHub Actions', category: 'tools', level: 'advanced' },
    { id: 'sk-8', name: 'Liderazgo Técnico', category: 'soft', level: 'expert' },
    { id: 'sk-9', name: 'Resolución de Problemas', category: 'soft', level: 'expert' },
  ],
  languages: [
    { id: 'lang-1', name: 'Español', proficiency: 'native' },
    { id: 'lang-2', name: 'Inglés', proficiency: 'advanced' },
    { id: 'lang-3', name: 'Francés', proficiency: 'basic' },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'PulseFlow Metrics',
      description:
        'Herramienta de observabilidad y monitoreo ligero para microservicios con alertas en tiempo real y gráficos en canvas.',
      role: 'Creador & Arquitecto',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'WebSockets'],
      link: 'https://pulseflow-demo.dev',
      github: 'https://github.com/amorales-dev/pulseflow',
      startDate: '2024-01',
      endDate: '2024-05',
    },
    {
      id: 'proj-2',
      name: 'OmniUI Design System',
      description:
        'Librería de componentes UI accesible y basada en tokens de diseño para agilizar el desarrollo frontend.',
      role: 'Autor principal',
      technologies: ['TypeScript', 'Tailwind CSS', 'Storybook', 'Vite'],
      link: 'https://omni-ui.dev',
      github: 'https://github.com/amorales-dev/omni-ui',
      startDate: '2023-08',
      endDate: '2023-11',
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      issueDate: '2023-10',
      expiryDate: '2026-10',
      credentialId: 'AWS-ASA-992147',
      credentialUrl: 'https://aws.amazon.com/verification',
    },
    {
      id: 'cert-2',
      name: 'Meta Front-End Developer Professional Certificate',
      issuer: 'Meta / Coursera',
      issueDate: '2022-04',
      credentialId: 'META-FED-88401',
    },
  ],
  sectionVisibility: {
    summary: true,
    experience: true,
    education: true,
    skills: true,
    languages: true,
    projects: true,
    certifications: true,
  },
};

export const INITIAL_EMPTY_CV: CVData = {
  id: 'cv-new',
  title: 'Mi Currículum',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  personalInfo: {
    fullName: '',
    jobTitle: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    linkedin: '',
    github: '',
    summary: '',
  },
  experiences: [],
  educations: [],
  skills: [],
  languages: [],
  projects: [],
  certifications: [],
  sectionVisibility: {
    summary: true,
    experience: true,
    education: true,
    skills: true,
    languages: true,
    projects: true,
    certifications: true,
  },
};
